TODO:
- Need longer data/ drop data for 1 year prime, 5 year prime, 6 month Govy
- train test split testing
- explained var??
- hyperparameterize models
- more models
- different data??

In [ ]:
import pandas as pd
import numpy as np
from datetime import timedelta
from datetime import datetime as dt

In [ ]:
#Import data
df = pd.read_csv('FinalDatasetPreMidterm.xlsx - Sheet1.csv')
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header
df

,Date,CPI,NaN,Date,Investment in Housing,NaN,Date,GDP,NaN,Date,...,1y Govy,NaN,Date,10y Govy,NaN,DATE,China Discount Rate,NaN,Date,Current Accounts
1,9/30/2023,-3.2,NaN,9/30/2023,-9.1,NaN,9/30/2023,5.2,NaN,11/1/2023,...,2.233,NaN,11/1/2023,2.686,NaN,1990-03-01,9,NaN,6/30/2023,64727.7
2,8/31/2023,-1.7,NaN,8/31/2023,-8.8,NaN,6/30/2023,5.5,NaN,10/31/2023,...,2.204,NaN,10/31/2023,2.689,NaN,1990-04-01,9,NaN,3/31/2023,81529.7
3,7/31/2023,-1.7,NaN,7/31/2023,-8.5,NaN,3/31/2023,4.5,NaN,9/29/2023,...,2.126,NaN,9/29/2023,2.673,NaN,1990-05-01,9,NaN,12/30/2022,103116.2
4,6/30/2023,2.3,NaN,6/30/2023,-7.9,NaN,12/31/2022,3,NaN,8/31/2023,...,1.867,NaN,8/31/2023,2.579,NaN,1990-06-01,9,NaN,9/30/2022,139636.4
5,5/31/2023,1,NaN,5/31/2023,-7.2,NaN,9/30/2022,3,NaN,7/31/2023,...,1.809,NaN,7/31/2023,2.659,NaN,1990-07-01,9,NaN,6/30/2022,73773.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-04-01,2.9,NaN,NaN,NaN
399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-05-01,2.9,NaN,NaN,NaN
400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-06-01,2.9,NaN,NaN,NaN
401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-01,2.9,NaN,NaN,NaN
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-08-01,2.9,NaN,NaN,NaN

In [ ]:
#seperate data
data = dict()
for i in range(0,len(df.columns),3):
  data[df.columns[i+1]] = df.iloc[:,i:i+2]

In [ ]:
data.keys()

dict_keys(['CPI', 'Investment in Housing', 'GDP', 'XAUUSD Curncy - Gold', 'Big China EtF', 'Brent Crude', 'WTI', 'Prime Loan 1y', 'Prime Loan 5y', 'Mining Value-Add', 'Manufacturing Value-Add', '6m Govy', '1y Govy', '10y Govy', 'China Discount Rate', 'Current Accounts'])

In [ ]:
for dataset in data:
  data[dataset] = data[dataset].dropna()
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])

<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])
<ipython-input-8-f2732504c13d>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data[dataset].iloc[:,0] = pd.to_datetime(data[dataset].iloc[:,0])

In [ ]:
#make this data End of Month
#Flip data to descending
data['China Discount Rate']['DATE'] = data['China Discount Rate']['DATE'] - timedelta(days=1)
data['China Discount Rate'].sort_values('DATE', ascending=0, inplace = True)
data['China Discount Rate'].rename(columns={"DATE":"Date"}, inplace=True)

In [ ]:
#account for potential data discrepancies in dates including weekends
#we do this by making data purely monthly
for dataset in data:
  data[dataset]['Date'] =  data[dataset]['Date'].dt.to_period('M')

In [ ]:
final_df = data['CPI']
for dataset in data:
  if dataset == 'CPI':
    continue
  else:
    final_df = final_df.merge(data[dataset], on='Date', how='outer')

In [ ]:
#drop prime loan 1, prime loan 5, 6 month govy as data is too short
final_df = final_df.drop(columns=['6m Govy','Prime Loan 1y', 'Prime Loan 5y'])

In [ ]:
#cut data
final_df = final_df[0:203] #cut to 2013 june
final_df = final_df[final_df['Date'].dt.year > 2012]
final_df = final_df[0:len(final_df)-5]
final_df

,Date,CPI,Investment in Housing,GDP,XAUUSD Curncy - Gold,Big China EtF,Brent Crude,WTI,Mining Value-Add,Manufacturing Value-Add,1y Govy,10y Govy,China Discount Rate,Current Accounts
0,2023-09,-3.2,-9.1,5.2,1848.63,18.92,95.31,90.79,1.5,5,2.126,2.673,NaN,NaN
1,2023-08,-1.7,-8.8,NaN,1940.19,19.37,86.86,83.63,2.3,5.4,1.867,2.579,NaN,NaN
2,2023-07,-1.7,-8.5,NaN,1965.09,21.2,85.56,81.8,1.3,3.9,1.809,2.659,2.9,NaN
3,2023-06,2.3,-7.9,5.5,1919.35,19.29,74.9,70.64,1.5,4.8,1.862,2.636,2.9,64727.7
4,2023-05,1,-7.2,NaN,1962.73,18.45,72.66,68.09,-1.2,4.1,1.989,2.706,2.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2013-10,6.5,19.2,NaN,1323.06,20.7,108.84,96.38,4.3,11.4,3.889,4.203,3.25,NaN
120,2013-09,6.1,19.7,7.8,1329.03,20.25,108.37,102.33,4.9,11.1,3.432,4.007,3.25,32587.4
121,2013-08,4.7,19.3,NaN,1395.27,19.24,114.01,107.65,5.8,10.9,3.6,4.018,3.25,NaN
122,2013-07,5,20.5,NaN,1325.07,18.78,107.7,105.03,5.5,10.5,3.448,3.732,3.25,NaN
123,2013-06,4.9,20.3,7.7,1234.53,18.06,102.16,96.56,5.8,9.6,3.395,3.53,3.25,42671.2

In [ ]:
#reset index
final_df.set_index('Date', inplace=True)
final_df.dtypes

0
CPI                        object
Investment in Housing      object
GDP                        object
XAUUSD Curncy - Gold       object
Big China EtF              object
Brent Crude                object
WTI                        object
Mining Value-Add           object
Manufacturing Value-Add    object
1y Govy                    object
10y Govy                   object
China Discount Rate        object
Current Accounts           object
dtype: object

In [ ]:
#change datatypes and interpolate
final_df = final_df.astype(float)
final_df.interpolate(method='linear', inplace=True)
final_df

,CPI,Investment in Housing,GDP,XAUUSD Curncy - Gold,Big China EtF,Brent Crude,WTI,Mining Value-Add,Manufacturing Value-Add,1y Govy,10y Govy,China Discount Rate,Current Accounts
Date,,,,,,,,,,,,,
2023-09,-3.2,-9.1,5.200000,1848.63,18.92,95.31,90.79,1.5,5.0,2.126,2.673,NaN,NaN
2023-08,-1.7,-8.8,5.300000,1940.19,19.37,86.86,83.63,2.3,5.4,1.867,2.579,NaN,NaN
2023-07,-1.7,-8.5,5.400000,1965.09,21.20,85.56,81.80,1.3,3.9,1.809,2.659,2.90,NaN
2023-06,2.3,-7.9,5.500000,1919.35,19.29,74.90,70.64,1.5,4.8,1.862,2.636,2.90,64727.700000
2023-05,1.0,-7.2,5.166667,1962.73,18.45,72.66,68.09,-1.2,4.1,1.989,2.706,2.90,70328.366667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-10,6.5,19.2,7.800000,1323.06,20.70,108.84,96.38,4.3,11.4,3.889,4.203,3.25,32380.433333
2013-09,6.1,19.7,7.800000,1329.03,20.25,108.37,102.33,4.9,11.1,3.432,4.007,3.25,32587.400000
2013-08,4.7,19.3,7.766667,1395.27,19.24,114.01,107.65,5.8,10.9,3.600,4.018,3.25,35948.666667
2013-07,5.0,20.5,7.733333,1325.07,18.78,107.70,105.03,5.5,10.5,3.448,3.732,3.25,39309.933333
2013-06,4.9,20.3,7.700000,1234.53,18.06,102.16,96.56,5.8,9.6,3.395,3.530,3.25,42671.200000

In [ ]:
#drop remaining nan
final_df = final_df.dropna()

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [ ]:
#build ols
X = final_df.drop(columns='China Discount Rate')
y = final_df['China Discount Rate']
XTr, XTe, yTr, yTe = train_test_split(X, y, test_size=0.2, random_state=69)
linear_model = LinearRegression().fit(XTr, yTr)
print("Training data model score:" , linear_model.score(XTr, yTr))
print("Testing data model score:" , linear_model.score(XTe, yTe))

Training data model score: 0.6761775513430344
Testing data model score: 0.7117426718882366

In [ ]:
rf_model = RandomForestRegressor(random_state=69).fit(XTr, yTr)
print("Training data model score:" , rf_model.score(XTr, yTr))
print("Testing data model score:" , rf_model.score(XTe, yTe))

Training data model score: 0.9884102564102561
Testing data model score: 0.9157999999999998

In [ ]:
#feature importance rf
# Access feature importances
feature_importances = rf_model.feature_importances_

# Create a DataFrame to display feature importances alongside feature names
feature_names = [f'{X.columns[i]}' for i in range(len(X.columns))]
importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})
importance_df = importance_df.sort_values(by='Importance', ascending=False)
importance_df

                    Feature  Importance
2                       GDP    0.387683
10                 10y Govy    0.289259
3      XAUUSD Curncy - Gold    0.144262
0                       CPI    0.051943
4             Big China EtF    0.027623
9                   1y Govy    0.026997
8   Manufacturing Value-Add    0.020848
6                       WTI    0.017930
5               Brent Crude    0.015282
1     Investment in Housing    0.009809
7          Mining Value-Add    0.006072
11         Current Accounts    0.002292